---
jobs:
  include:
    - os: linux
      language: python
      python:
        - "3.8"
      arch: amd64
      dist: focal
  before_install:
    - sudo apt-get -y install libxml2-dev
script:
  - python hello_world.py
